Internet programming languages/LR12/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  post 'sessions/create'
  get 'sessions/logout'
  get 'view', to: 'lucky_nums#view'
  resources :users, only: %i[ new create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lucky_nums#input"
end

Internet programming languages/LR12/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Internet programming languages/LR12/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :login, message: 'Имя пользователя уже существует'
  validates_presence_of :login, message: 'Имя пользователя не должно быть пустым'
  validates_presence_of :password, message: 'Пароль пользователя не должно быть пустым'
  validates_confirmation_of :password
end

Internet programming languages/LR12/app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :require_login

  def require_login
    redirect_to sessions_login_path unless signed_in?
  end
end

Internet programming languages/LR12/app/controllers/lucky_nums_controller.rb
# frozen_string_literal: true

# LuckyNumsController
class LuckyNumsController < ApplicationController
  before_action :parse_and_validate, only: :view

  def input; end

  def view
    flash.clear
    @lucky_nums = {}
    0.upto(@num.to_i) do |i|
      i_str = i.to_s
      i_str.insert(0, '0' * (6 - i_str.length))
      l_sum = helpers.calc_sum(i_str, 0, 3)
      r_sum = helpers.calc_sum(i_str, 3, 6)
      @lucky_nums[i] = l_sum if l_sum == r_sum
    end
  end

  private

  def parse_and_validate
    @num = params[:num]
    return unless @num !~ /\A[1-9][0-9]{0,}\z/

    redirect_to(lucky_nums_input_path,
                alert: 'Переданное число должно быть целым и положительным')
  end
end

Internet programming languages/LR12/app/controllers/sessions_controller.rb
# frozen_string_literal: true

# SessionsController
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login; end

  def create
    user = User.find_by_login(params[:login])
    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      flash[:alert] = user.nil? ? 'Неправильный логин' : 'Неправильный пароль'
      redirect_to sessions_login_path
    end
  end

  def logout
    sign_out
    redirect_to sessions_login_path
  end
end

Internet programming languages/LR12/app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[create new edit]

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    sign_in @user
    respond_to do |format|
      if @user.save
        format.html { redirect_to sessions_login_path, notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

Internet programming languages/LR12/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

Internet programming languages/LR12/app/helpers/lucky_nums_helper.rb
# frozen_string_literal: true

# Helper for LuckyNums
module LuckyNumsHelper
  def calc_sum(num, left, right)
    sum = 0
    num[left, right].each_char { |c| sum += c.to_i }
    sum
  end
end

Internet programming languages/LR12/app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Helper for Sessions
module SessionsHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 7.days }
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

Internet programming languages/LR12/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

Internet programming languages/LR12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LR12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Internet programming languages/LR12/app/views/lucky_nums/input.html.erb
<% flash.each do |_, msg| %>
    <h1 id="error"><%= msg %></h1>
<% end %>
<%= form_with url: view_path, method: :get do |form| %>
    <%= form.label :num, 'Введите верхнюю границу проверки чисел (> 0):', id: 'input-label' %>
    <%= form.text_field :num %>
    <br>
    <br>
    <%= form.submit 'Проверить' %>
<% end %>
<br>
<br>
<%= link_to 'Выйти', sessions_logout_path %>

Internet programming languages/LR12/app/views/lucky_nums/view.html.erb
<%= link_to 'Вернуться к вводу', root_path %>
<br>
<br>
<table border = "1">
    <thead>
        <th>Число</th>
        <th>Сумма слева и справа</th>
    </thead>
    <% @lucky_nums.each_pair do |num, sum| %>
    <tr>
        <td><%= num %></td>
        <td><%= sum %></td>
    </tr>
    <% end %>
</table>

Internet programming languages/LR12/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :login, 'Введите логин: ' %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.label :password, 'Введите пароль: ' %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, 'Повторите пароль: ' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Internet programming languages/LR12/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Вернуться", sessions_login_path %>
</div>