Internet programming languages/LR8/config/routes.rb
Rails.application.routes.draw do
  root 'lucky_nums#input'
  get 'lucky_nums', to: 'lucky_nums#view'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Internet programming languages/LR8/app/controllers/lucky_nums_controller.rb
# frozen_string_literal: true

# Lucky Nums Controller
class LuckyNumsController < ApplicationController
  before_action :validate_num, only: :view

  def input; end

  def view
    @n = params[:num].to_i
    @lucky_nums = {}
    0.upto(@n) do |i|
      i_str = i.to_s
      i_str.insert(0, '0' * (6 - i_str.length))
      @lucky_nums[i] = helpers.calc_sum(i_str, 0, 3) if helpers.calc_sum(i_str, 0, 3) == helpers.calc_sum(i_str, 3, 6)
    end
  end

  private

  def validate_num
    redirect_to(root_path, alert: 'Ошибка! Число должно быть > 0') if params[:num].to_i.negative?
  end
end

Internet programming languages/LR8/app/helpers/lucky_nums_helper.rb
# frozen_string_literal: true

# Helper for LuckNums
module LuckyNumsHelper
  def calc_sum(num, left, right)
    sum = 0
    num[left, right].each_char { |c| sum += c.to_i }
    sum
  end
end

Internet programming languages/LR8/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LR8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Internet programming languages/LR8/app/views/lucky_nums/input.html.erb
<h1>LuckyNums#input</h1>
<p>Find me in app/views/lucky_nums/input.html.erb</p>
<% flash.each do |_, msg| %>
    <h1><%= msg %></h1>
<% end %>
<%= form_with url: lucky_nums_path, method: :get do |form| %>
    <%= form.label :num, 'Введите верхнюю границу проверки чисел (> 0):' %>
    <%= form.text_field :num %>
    <br>
    <br>
    <%= form.submit 'Проверить' %>
<% end %>

Internet programming languages/LR8/app/views/lucky_nums/view.html.erb
<h1>LuckyNums#view</h1>
<p>Find me in app/views/lucky_nums/view.html.erb</p>
<p>Счастливые числа до <%= @n %> </p>
<%= link_to 'Вернуться к вводу', root_path %>
<br>
<br>
<table border = "1">
    <thead>
        <th>Число</th>
        <th>Сумма слева и справа</th>
    </thead>
    <% @lucky_nums.each_key do |key| %>
    <tr>
        <td><%= key %></td>
        <td><%= @lucky_nums[key] %></td>
    </tr>
    <% end %>
</table>